use_frameworks!

platform :ios, '8.0'

target 'YHTextView_Example' do
  pod 'YHTextView', :path => '../'

  target 'YHTextView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
